### ISSUE TITLE
Where is Kerberos?

### ISSUE THREAD

**Issue by splincode** [teesloane/Auth-Boss#11]
My team at work we were able to enter the local machine to the Active Directory domain that checks the user login and password for the Kerberos protocol. The application works in a browser.

**Comment by drcolombo** [comment]
Kerberos is actually an implementation of token-based (token there is called ticket) authentication made by Microsoft and used only in intranet (or if you establish a VPN connection, so you're in intranet anyway) based on Windows server. It's not supported by many proxy servers, as well as by Java, as it's not described in RFC-2069 for proxy authentication.
Extremely simple explanation of the difference between classic token-based authentication is that in Windows environment the Kerberos ticket is issued not when you are authenticated by a browser but when you're logged in to your Windows account (although can be re-issued by a special request) and it's stored in your Windows, not in a browser.

**Comment by pashkinmv** [comment]
Kerberos is actually a protocol developed in [MIT](https://www.google.ru/search?q=kerberos&oq=kerberos&aqs=chrome..69i57j0j69i59l2j0l2.1901j1j4&sourceid=chrome&ie=UTF-8). Current version is 5.
Almost all OS have it's implementation, not only Windows server, including GSS-API (RFC 2853). Java has implementation of this RFC. Read [here](https://www.google.ru/search?q=kerberos+java+implementation&oq=kerberos+java+imp&aqs=chrome.1.69i57j0l3.8841j1j7&sourceid=chrome&ie=UTF-8), [here](http://docs.oracle.com/javase/jndi/tutorial/ldap/security/gssapi.html) and [here](https://docs.oracle.com/javase/8/docs/technotes/guides/security/jgss/single-signon.html).
Browser delegates OS to request required TGT from TGS and passes it (TGT) to server if required.
The only server needs to support SSO is to send specified headers and decode received TGT. Google existing implementations.

p.s. Kerberos uses principle of token based authentication

> if i was you i wanna be me too

**Comment by drcolombo** [comment]
Yes, you're right, but the topic starter asked about Active Directory, so my comment was exactly about Microsoft implementation.
