### ISSUE TITLE
OAuth 2.0 is not an authentication protocol

### ISSUE THREAD

**Issue by aliasaria** [teesloane/Auth-Boss#4]
OAuth docs clearly state:

"OAuth 2.0 is not an authentication protocol."

Here: https://oauth.net/articles/authentication/

So perhaps it would be better for you to change the text to "OAuth is an authorization protocol" and then perhaps link to the above document for the sake of pedants.

**Comment by teesloane** [comment]
That sounds good! Thanks for point that out. I will add this shortly.

**Comment by rohannair** [comment]
@aliasaria @teesloane - might be even better to go into the difference of authorization vs authentication

`Authentication` - Proving who you are
`Authorization` - Determining what you have permission to do

It's a really important difference.

P.S. @aliasaria love that you're still kicking it on Github haha

**Comment by teesloane** [comment]
@aliasaria @rohannair 

These are both great points and I will certainly make some amendments. Thanks for the input!

**Comment by dhuyen79** [comment]
https://github.com/teesloane/Auth-Boss/commit/5715e939961bfcb964e419a35087b1de680ff164
